### ISSUE TITLE
What about creating a project to make it easy using  community_store_api?

### ISSUE THREAD

**Issue by mlocati** [concrete5-community-store/community_store_api#12]
@Mesuva I'm thinking about a library that makes it easy to use community_store_api.

That library would:

1. offer a client that lets you perform requests easily
2. provide entities to represent objects
3. work with concrete5 v8 (which uses the Zend HTTP client), with ConcreteCMS v9 (which uses Guzzle as an HTTP client) and in non-concrete projects

I'd publish it under https://github.com/concretecms-community-store/community_store_api_client

**Comment by Mesuva** [comment]
Would it be a library that you would add to an add-on (via composer), to make it easier to consume the API data?
(instead of having to repeatedly write lower-level client code each time)

**Comment by mlocati** [comment]
It'd be a library that you can use with composer-based projects, and that would allow you to write something like this:

```php
use CommunityStore\APIClient;

$client = new APIClient\Client();

$storeConfig = $client->getConfig(); // calls the cs/api/v1/config endpoint

$searchOptions = new APIClient\Order\SearchOptions();
$searchOptions->setOrderStatus(APIClient\Order\Status::Delivered);
$orders = $client->getOrders($searchOptions); // calls the cs/api/v1/orders endpoint
echo $orders[0]->getID();
```

**Comment by mlocati** [comment]
Something like this: https://github.com/mlocati/community_store_api_client

PS: everything should work, except the `/products...`, `/skus...`, and `/variations...` routes which are not implemented.

**Comment by mlocati** [comment]
@Mesuva if [the project above](https://github.com/concretecms-community-store/community_store_api/issues/12#issuecomment-1910184662) is ok for you, what about moving it to the https://github.com/concretecms-community-store organization and publishing it on packagist?

**Comment by Mesuva** [comment]
I'm certainly open to moving it to the CS organization, no issues there.

I just haven't been able to view the repo, as https://github.com/mlocati/community_store_api_client 404s for me.

**Comment by mlocati** [comment]
Whoops, it was still private 😉

**Comment by Mesuva** [comment]
That's really cool
Go ahead an action anything you need to to move the repo. (I know we did one not long ago, but I've forgotten the steps)

**Comment by mlocati** [comment]
Done!
I've also added it to packagist - see https://packagist.org/packages/concretecms-community-store/community_store_api_client , but it seems the auto-update feature doesn't work.
I think the problem is that I'm not ad admin of the moved repo: here's what packagist tells me:

![immagine](https://github.com/concretecms-community-store/community_store_api/assets/928116/096d7939-945e-42ea-9403-f55bac83ec9a)

**Comment by mlocati** [comment]
Yep, the problem is that I don't have admin rights [on the repo I moved](https://github.com/concretecms-community-store/community_store_api_client).

@Mesuva could you grant me admin rights? That way I can also publish a first version.

**Comment by Mesuva** [comment]
@mlocati I just changed that, let me know if you need anything else changed

**Comment by mlocati** [comment]
Perfect, thanks! Everything seems just fine now!
