### ISSUE TITLE
Installation confusion

### ISSUE THREAD

**Issue by RayGan0303** [concrete5-community-store/community_store_api#17]
The readme says "Once installed, the Community Store API is accessed...", but I can't see which files and/or directory structure I need from the github repository to be able to ftp to my site and install using the Concrete5 "Add functionality" page.
(It may be there but I haven't been able to find a corresponding package on the C5 marketplace.)

Guidance would be greatly appreciated. 

Thanks for a giving us such great tool in Community Store.

Ray

**Comment by Mesuva** [comment]
Download the release zip from here:
https://github.com/concretecms-community-store/community_store_api/releases/tag/v1.0.4
Unzip it to your packages directory, making sure the folder name is just community_store_api
Install it via the Extend Concrete section of the dashboard

Then you'd just go from here: https://github.com/concretecms-community-store/community_store_api?tab=readme-ov-file#setup

**Comment by RayGan0303** [comment]
Thanks Ryan, both for the answer and prompt replay
