### ISSUE TITLE
Sale Price

### ISSUE THREAD

**Issue by mikthemonster** [concrete5-community-store/community_store_api#2]
How can I get Sale Price of a product? It looks like Sale Price is not part of API??

URL:
/cs/api/v1/products

**Comment by Mesuva** [comment]
This was just an oversight, I've added the output of the sale price here:
https://github.com/concrete5-community-store/community_store_api/commit/c17de0800ef2a32ad1711e3d7213a224e1f1a3a9

**Comment by mikthemonster** [comment]
Thanks a lot!

**Comment by mlocati** [comment]
This issue can be closed, right?
