### ISSUE TITLE
Add to packagist?

### ISSUE THREAD

**Issue by mlocati** [concrete5-community-store/community_store_api#3]
What about adding a composer.json file and submitting this package to packagist? That way, we could install it via composer...

**Comment by Mesuva** [comment]
There used to be a reason why I thought this was problematic, but I think that's no longer the case.
So yes, I'd certainly open to it being available on packagist. 

I just personally can't remember the process, as it's been a long time since I've submitted something...

**Comment by mlocati** [comment]
> I just personally can't remember the process, as it's been a long time since I've submitted something...

It's as easy as adding a composer.json file (see #6) and [submitting the repository to packagist](https://packagist.org/packages/submit) :wink:

**Comment by mlocati** [comment]
Done, thanks!!!

PS: what about a new version? There are some changes since the latest one: see https://github.com/concretecms-community-store/community_store_api/compare/v1.0.1...master
